### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [saninstein/test#4]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.7. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary simple-sum -w /tmp/ext simple-sum==0.0.7
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting simple-sum==0.0.7
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/f28/5b417f3edca76/simple-sum-0.0.7.tar.gz (1.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ejq55tg2/simple-sum/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ejq55tg2/simple-sum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ejq55tg2/simple-sum/pip-egg-info
         cwd: /tmp/pip-wheel-ejq55tg2/simple-sum/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ejq55tg2/simple-sum/setup.py", line 6, in <module>
        with open('.version') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '.version'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by saninstein** [comment]
Thanks! I'll keep it on mind.

**Comment by thatch** [comment]
I tried to autofix this but can't test because of the underscored name you're importing from pip.  Basically it just needs "include .version" in a MANIFEST.in file in the root.
